namespace DynaFill.Filler
{
    public static class PreSetData
    {
        public static string[] GetHumanNames()
        {
            return new string[]
            {
                "Abbas",
                "Abdallah",
                "Abdalroof",
                "Abdihakim",
                "Abdirahman",
                "Abdul-Aziz",
                "Abdul-Basir",
                "Abdul-Kadir",
                "Abdul-Karim",
                "Abdullah",
                "Abdul-Majeed",
                "Abdul-Malik",
                "Abdul-Rahim",
                "Abdul-Rahman",
                "Abdul-Rehman",
                "Abdul-Salam",
                "Ahmad",
                "Akram",
                "Ashraf",
                "Azzam",
                "Bader",
                "Badr",
                "Baha",
                "Bara",
                "Bashir",
                "Bilal",
                "Burhan",
                "Dawoud",
                "Ehsan",
                "Essa",
                "Essam",
                "Fadi",
                "Fahad",
                "Fahmi",
                "Faisal",
                "Faiz",
                "Fares",
                "Farid",
                "Fathi",
                "Fawwaz",
                "Fayez",
                "Fazli",
                "Fouad",
                "Ghassan",
                "Ghiyath",
                "Hafeez",
                "Haidar",
                "Haitham",
                "Hakam",
                "Hamdi",
                "Hamid",
                "Hani",
                "Harith",
                "Harun",
                "Hasan",
                "Hassan",
                "Hazim",
                "Hilmi",
                "Husam",
                "Hussein",
                "Ibrahim",
                "Idris",
                "Ihsan",
                "Ilyas",
                "Imad",
                "Imran",
                "Iqbal",
                "Ishaq",
                "Iskandar",
                "Ismail",
                "Iyad",
                "Jabbar",
                "Jabir",
                "Jafar",
                "Jalal",
                "Jamal",
                "Jameel",
                "Jawad",
                "Jawid",
                "Jibril",
                "Jihad",
                "Kamal",
                "Karam",
                "Karim",
                "Khaldun",
                "Khalid",
                "Khalil",
                "Khamis",
                "Laith",
                "Luay",
                "Lutfi",
                "Mahdi",
                "Mahmud",
                "Majid",
                "Mamduh",
                "Manaf",
                "Marwan",
                "Mayar",
                "Maysarah",
                "Mazen",
                "Mohammed",
                "Muhsin",
                "Muin",
                "Munir",
                "Muntasir",
                "Murtada",
                "Mustafa",
                "Muzaffar",
                "Nabil",
                "Najeeb",
                "Naji",
                "Najm",
                "Nasir",
                "Nasser",
                "Nawfal",
                "Nazih",
                "Nazim",
                "Nizar",
                "Nuri",
                "Omar",
                "Osama",
                "Othman",
                "Qasim",
                "Qays",
                "Qusay",
                "Rafi",
                "Raghib",
                "Raid",
                "Rami",
                "Rashad",
                "Rashid",
                "Rasim",
                "Rebhi",
                "Rida",
                "Ridwan",
                "Rushdi",
                "Saad",
                "Sadiq",
                "Saeed",
                "Sajid",
                "Salah",
                "Saleh",
                "Salim",
                "Salman",
                "Sami",
                "Samir",
                "Suhail",
                "Sulaiman",
                "Taha",
                "Taher",
                "Tahri",
                "Tahsin",
                "Talal",
                "Talib",
                "Tariq",
                "Tawfiq",
                "Tayeb",
                "Tayem",
                "Taysir",
                "Thabit",
                "Thaqib",
                "Tharwat",
                "Ubay",
                "Uday",
                "Wadud",
                "Wafi",
                "Wafiq",
                "Wahbi",
                "Wahib",
                "Wahid",
                "Wail",
                "Wajdi",
                "Wajih",
                "Wathiq",
                "Wisam",
                "Yahya",
                "Yakub",
                "Yaman",
                "Yamin",
                "Yanal",
                "Yasar",
                "Yasin",
                "Yasir",
                "Yunus",
                "Yusuf",
                "Zahed",
                "Zahir",
                "Zaid",
                "Zakariya",
                "Zaki",
                "Ziyad",
                "Zuhayr",
                "Zuhdi"
            };
        }

        public static string[] GetJobTitleNames()
        {
            return new string[]
            {
                "Accountant",
                "Administrative Assistant",
                "Baker",
                "Barista",
                "Business Analyst",
                "Carpenter",
                "Cashier",
                "Chef",
                "Cleaner",
                "Construction Worker",
                "Database Administrator",
                "Dentist",
                "Doctor",
                "Driver",
                "Electrician",
                "Farmer",
                "Financial Analyst",
                "Gardener",
                "Human Resources Officer",
                "Internal Auditor",
                "Librarian",
                "Logistics Coordinator",
                "Maintenance Worker",
                "Marketing Specialist",
                "Mason",
                "Mechanic",
                "Nurse",
                "Painter",
                "Pharmacist",
                "Physiotherapist",
                "Plumber",
                "Professor",
                "Psychologist",
                "Receptionist",
                "Sales Representative",
                "Secretary",
                "Security Guard",
                "Social Worker",
                "Software Engineer",
                "Teacher",
                "Veterinarian",
                "Waiter",
                "Warehouse Worker",
                "Web Developer",
                "Welder",
            };
        }

        public static string[] GetDepartmentNames()
        {
            return new string[] {
                "Accounting",
                "Administration",
                "Business Development",
                "Customer Service",
                "Engineering",
                "Finance",
                "Human Resources",
                "Information Technology",
                "Legal",
                "Marketing",
                "Operations",
                "Product Management",
                "Production",
                "Quality Assurance",
                "Research and Development",
                "Sales",
                "Support",
                "Training",
            };
        }

        public static string[] GetCompanyNames()
        {
            return new string[]
            {
                "ABC Company",
                "DEF Company",
                "GHI Company",
                "JKL Company",
                "MNO Company",
                "PQR Company",
                "STU Company",
                "VWX Company",
                "XYZ Company"
            };
        }
    }
}
